export REPOS="$XDG_DATA_HOME/repos"

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CMAKE_PREFIX="$HOME/.local"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --border=sharp --no-scrollbar"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export LESS="-iMRx4 -j.5"
export MANPAGER="nvim +Man!"
export PASSWORD_STORE_DIR="$REPOS/password-store"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SWIFTLY_BIN_DIR="$HOME/.local/bin"
export SWIFTLY_HOME_DIR="$XDG_DATA_HOME/swiftly"
export SWIFTLY_TOOLCHAINS_DIR="$XDG_DATA_HOME/swiftly/toolchains"
