env = SDL_VIDEODRIVER,wayland

execr-once = nextcloud --background
execr-once = systemctl --user start pipewire

bind = $mainMod, Backspace, exec, rofi -show drun -replace -i # Application launcher

cursor {
  hide_on_key_press = true
}

input {
  kb_options = caps:swapescape
  repeat_delay = 300
  repeat_rate = 30
}
